reference:
  "/path/to/ref/genome/hs37d5.fasta"
backbones:
  "/path/to/data/backbones.fasta"
input_dir:
  "/path/to/input/bam"
out_dir:
  "/path/to/NanoRCS/output/processed_data/01_preprocess_nanorcs/consensus_filtered"
sample_tsv:
  "/path/to/samplesheet_example.csv"